### ISSUE TITLE
Test cases for output

### ISSUE THREAD

**Issue by ledlogic** [jtenner/e2d#6] opened 2015-09-24 12:24 UTC
Could you have test case of exporting to png or jpg?

**Comment by jtenner** [comment] 2015-09-24 16:29
@ledlogic what exactly are you looking for?

The `renderer.toImage()` function exports only to type `Img`.

```javascript
  var img = renderer.toImage();
  img.cache();

  renderer.render(
   e2d.fillImage(img)
  );
```

If you are on the browser side (not in a web worker) you can access the dataurl yourself on the properties of the `Img` object here.

```javascript
var img = renderer.toImage();
var src = img.imageElement.src;
```

This is a synchronous API that would only work in the browser.

Do you need access to the dataurl yourself?

```javascript
r.exportTo('png', function(dataurl) { //accepts png, or jpg
  //dataurl is a string and works inside a webworker
});
r.exportTo('buffer', function(data) {
   //basically ctx.getImageData
});

```

**Comment by ledlogic** [comment] 2015-09-25 15:53
I guess I am too new to imagery in node.js, and was expecting that if I want to provide an image service as a web process, I'd need to return "image/png" data to the client.  Maybe there are other libraries you'd then use to complete the r.exportTo implementation to jpg or png, outside of e2d?

**Comment by jtenner** [comment] 2015-09-25 15:58
@ledlogic  this doesn't run inside node.js, it does however run inside nw.js and the browser.  I think you  need node-canvas.

**Comment by jtenner** [comment] 2015-10-07 20:18
I'm going to close this issue, as I'm not exactly sure what the problem is.  I'd be more than happy to reopen it.

Cheers,
-Josh

**Closed by jtenner** 2015-10-07 20:18 UTC
